#:schema https://json.schemastore.org/rust-toolchain.json

[toolchain]
channel = "stable"
# https://rust-lang.github.io/rustup/concepts/components.html
components = [
	  "rust-src", # for rust-analyzer
      "rust-analyzer",
	  "cargo",
	  "rustc",
	  "rustfmt",
	  "clippy",
	  "rust-docs",
]
targets = [
	# 64bits Linux Desktop
	"x86_64-unknown-linux-gnu",
	# Web Assembly
	"wasm32-unknown-unknown",
	# Android
	"aarch64-linux-android",
	"armv7-linux-androideabi",
	# iOS
	"aarch64-apple-ios",
	"x86_64-apple-ios",
	"aarch64-apple-ios-sim"
	# 64bits RPI4
	# "aarch64-unknown-linux-gnu",
	# 32bits RPI4
	# "armv7-unknown-linux-gnueabihf",
]
